# Generated by Selenium IDE
import unittest
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Testlogin(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Chrome("chromedriver.exe")
        self.driver.get("http://demo.guru99.com/test/newtours/")

    def test_success_login(self):
        self.driver.find_element(By.NAME, "userName").click()
        self.driver.find_element(By.NAME, "userName").send_keys("user")
        self.driver.find_element(By.NAME, "password").click()
        self.driver.find_element(By.NAME, "password").send_keys("pass")
        self.driver.find_element(By.NAME, "submit").click()

        x= 1
        y= 1
        assert x == y

    def test_fail_login(self):
        self.driver.find_element(By.NAME, "userName").click()
        self.driver.find_element(By.NAME, "userName").send_keys("Usuario")
        self.driver.find_element(By.NAME, "password").click()
        self.driver.find_element(By.NAME, "password").send_keys("123456")
        self.driver.find_element(By.NAME, "submit").click()

        x= 1
        y= 2
        assert x != y

    def tearDown(self):
        # self.driver.quit()
        self.driver.close()


if __name__ == "__main__":
    unittest.main()
